version: '3.7'
services:
  mongo1:
    image: mongo:4.0.9
    ports:
      - 30001:30001
    volumes:
      - ./mongocluster/mongo1:/data/db
    networks:
      - mongocluster
    command: mongod --replSet sample --port 30001 --smallfiles
  mongo2:
    image: mongo:4.0.9
    ports:
      - 30002:30002
    volumes:
      - ./mongocluster/mongo2:/data/db
    networks:
      - mongocluster
    command: mongod --replSet sample --port 30002 --smallfiles
    depends_on:
      - mongo1
  mongo3:
    image: mongo:4.0.9
    ports:
      - 30003:30003
    volumes:
      - ./mongocluster/mongo3:/data/db
    networks:
      - mongocluster
    command: mongod --replSet sample --port 30003 --smallfiles
    depends_on:
      - mongo2
networks:
  mongocluster:
    driver: bridge
